# Generated by Django 5.2.6 on 2025-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('legwears', 'Legwears'), ('accessories', 'Accessories')], default='update', max_length=20),
        ),
    ]
